begin;
create extension if not exists pgcrypto;
create table if not exists public.travel_plans (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null check(char_length(trim(name)) between 1 and 100), start_date date not null, end_date date not null, invite_code text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint valid_plan_dates check(end_date>=start_date));
create table if not exists public.plan_days (id uuid primary key default gen_random_uuid(), plan_id uuid not null references public.travel_plans(id) on delete cascade, date date not null, position integer not null default 0 check(position>=0), unique(plan_id,date));
create table if not exists public.itinerary_cards (id uuid primary key default gen_random_uuid(), day_id uuid not null references public.plan_days(id) on delete cascade, title text not null check(char_length(trim(title))>0), location text not null check(char_length(trim(location))>0), start_time time not null, category text not null default 'Sightseeing', description text not null default '', latitude double precision not null check(latitude between -90 and 90), longitude double precision not null check(longitude between -180 and 180), position integer not null default 0 check(position>=0), route_distance_m double precision, route_duration_s double precision, route_geometry jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.plan_members (plan_id uuid not null references public.travel_plans(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member' check(role in ('admin','member')), joined_at timestamptz not null default now(), primary key(plan_id,user_id));
alter table public.travel_plans add column if not exists revision bigint not null default 0;
alter table public.plan_members add column if not exists display_name text;
create index if not exists plan_days_plan_idx on public.plan_days(plan_id,date); create index if not exists itinerary_cards_day_idx on public.itinerary_cards(day_id,position); create index if not exists plan_members_user_idx on public.plan_members(user_id);

create or replace function public.is_plan_member(target_plan uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from plan_members where plan_id=target_plan and user_id=auth.uid()) or exists(select 1 from travel_plans where id=target_plan and owner_id=auth.uid()) $$;
create or replace function public.is_plan_admin(target_plan uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from travel_plans where id=target_plan and owner_id=auth.uid()) or exists(select 1 from plan_members where plan_id=target_plan and user_id=auth.uid() and role='admin') $$;
create or replace function public.add_owner_as_admin() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into plan_members(plan_id,user_id,role) values(new.id,new.owner_id,'admin') on conflict do nothing; return new; end $$;
drop trigger if exists travel_plan_owner_membership on public.travel_plans; create trigger travel_plan_owner_membership after insert on public.travel_plans for each row execute function public.add_owner_as_admin();
create or replace function public.join_travel_plan(invite_pin text) returns uuid language plpgsql security definer set search_path=public as $$ declare target uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; select id into target from travel_plans where upper(invite_code)=upper(trim(invite_pin)); if target is null then raise exception 'invalid invite code'; end if; insert into plan_members(plan_id,user_id,role) values(target,auth.uid(),'member') on conflict do nothing; return target; end $$;
create or replace function public.claim_plan_revision(target_plan uuid, expected_revision bigint) returns bigint language plpgsql security definer set search_path=public as $$ declare next_revision bigint; begin if not public.is_plan_member(target_plan) then raise exception 'plan access denied'; end if; update travel_plans set revision=revision+1,updated_at=now() where id=target_plan and revision=expected_revision returning revision into next_revision; return next_revision; end $$;
create or replace function public.leave_travel_plan(target_plan uuid, new_owner uuid default null) returns void language plpgsql security definer set search_path=public as $$ declare current_owner uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; select owner_id into current_owner from travel_plans where id=target_plan; if current_owner is null or not public.is_plan_member(target_plan) then raise exception 'plan access denied'; end if; if current_owner=auth.uid() then if new_owner is null or not exists(select 1 from plan_members where plan_id=target_plan and user_id=new_owner and role='admin') then raise exception 'transfer admin rights before leaving'; end if; update travel_plans set owner_id=new_owner,revision=revision+1,updated_at=now() where id=target_plan; end if; delete from plan_members where plan_id=target_plan and user_id=auth.uid(); end $$;

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists touch_travel_plans_updated_at on public.travel_plans; create trigger touch_travel_plans_updated_at before update on public.travel_plans for each row execute function public.touch_updated_at();
drop trigger if exists touch_itinerary_cards_updated_at on public.itinerary_cards; create trigger touch_itinerary_cards_updated_at before update on public.itinerary_cards for each row execute function public.touch_updated_at();

alter table public.travel_plans enable row level security; alter table public.plan_days enable row level security; alter table public.itinerary_cards enable row level security; alter table public.plan_members enable row level security;
drop policy if exists "members read plans" on public.travel_plans; drop policy if exists "owners manage plans" on public.travel_plans; drop policy if exists "owners create plans" on public.travel_plans; drop policy if exists "admins update plans" on public.travel_plans; drop policy if exists "admins delete plans" on public.travel_plans;
create policy "members read plans" on public.travel_plans for select to authenticated using(owner_id=auth.uid() or public.is_plan_member(id)); create policy "owners create plans" on public.travel_plans for insert to authenticated with check(owner_id=auth.uid()); create policy "admins update plans" on public.travel_plans for update to authenticated using(owner_id=auth.uid() or public.is_plan_admin(id)) with check(owner_id=auth.uid() or public.is_plan_admin(id)); create policy "admins delete plans" on public.travel_plans for delete to authenticated using(owner_id=auth.uid() or public.is_plan_admin(id));
drop policy if exists "members read days" on public.plan_days; drop policy if exists "members manage days" on public.plan_days; create policy "members manage days" on public.plan_days for all using(public.is_plan_member(plan_id)) with check(public.is_plan_member(plan_id));
drop policy if exists "members manage cards" on public.itinerary_cards; create policy "members manage cards" on public.itinerary_cards for all using(exists(select 1 from plan_days d where d.id=day_id and public.is_plan_member(d.plan_id))) with check(exists(select 1 from plan_days d where d.id=day_id and public.is_plan_member(d.plan_id)));
drop policy if exists "members see membership" on public.plan_members; drop policy if exists "members read membership" on public.plan_members; drop policy if exists "admins manage membership" on public.plan_members; create policy "members read membership" on public.plan_members for select using(public.is_plan_member(plan_id)); create policy "admins manage membership" on public.plan_members for all using(public.is_plan_admin(plan_id)) with check(public.is_plan_admin(plan_id));
grant usage on schema public to authenticated; grant select,insert,update,delete on public.travel_plans,public.plan_days,public.itinerary_cards,public.plan_members to authenticated;
revoke all on function public.is_plan_member(uuid), public.is_plan_admin(uuid), public.add_owner_as_admin(), public.join_travel_plan(text), public.claim_plan_revision(uuid,bigint), public.leave_travel_plan(uuid,uuid) from public, anon;
grant execute on function public.is_plan_member(uuid), public.is_plan_admin(uuid), public.join_travel_plan(text), public.claim_plan_revision(uuid,bigint), public.leave_travel_plan(uuid,uuid) to authenticated;
do $$ begin alter publication supabase_realtime add table public.travel_plans; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.plan_days; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.itinerary_cards; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.plan_members; exception when duplicate_object then null; end $$;
commit;
