import 'package:flutter/widgets.dart';

class AppLocalization {
  const AppLocalization(this.locale);

  final Locale locale;

  static AppLocalization of(BuildContext context) =>
      AppLocalization(Localizations.localeOf(context));

  static const Map<String, Map<String, String>> _values = {
    'ms': {
      'Discover': 'Terokai',
      'Map': 'Peta',
      'Mystery': 'Misteri',
      'Plan': 'Pelan',
      'Profile': 'Profil',
      'Language': 'Bahasa',
      'Language Settings': 'Tetapan Bahasa',
      'Back': 'Kembali',
      'Create plan': 'Cipta pelan',
      'Export PDF': 'Eksport PDF',
      'Edit profile': 'Sunting profil',
      'Photo, name and travel bio': 'Foto, nama dan biodata perjalanan',
      'Achievements & badges': 'Pencapaian & lencana',
      'Challenges, progress and rewards': 'Cabaran, kemajuan dan ganjaran',
      'Passport stamps': 'Cop pasport',
      'Your verified destination collection': 'Koleksi destinasi disahkan anda',
      'Log out': 'Log keluar',
      'Explore Discover': 'Terokai penemuan',
      'Add to Plan': 'Tambah ke pelan',
      'Get Directions': 'Dapatkan arah',
      'Clear all': 'Kosongkan semua',
      'Reset filters': 'Tetapkan semula penapis',
      'Write Review': 'Tulis ulasan',
      'Submit Review': 'Hantar ulasan',
      'Heritage Quest': 'Misi warisan',
      'Retry': 'Cuba lagi',
      'Cancel': 'Batal',
      'Edit': 'Sunting',
      'Resume': 'Sambung',
      'Save preferences': 'Simpan pilihan',
      'View on Map': 'Lihat pada peta',
      'View Passport': 'Lihat pasport',
      'Explore Another Mystery': 'Terokai misteri lain',
      'Create New Plan': 'Cipta pelan baharu',
      '+ Create New Plan': '+ Cipta pelan baharu',
      'Create Travel Plan': 'Cipta pelan perjalanan',
      'Add Activity': 'Tambah aktiviti',
      'Add Date Tab': 'Tambah tab tarikh',
      'Join Plan': 'Sertai pelan',
      'Delete Plan': 'Padam pelan',
      'Delete': 'Padam',
      'Share': 'Kongsi',
      'Remove': 'Alih keluar',
      'Leave Group': 'Tinggalkan kumpulan',
      'Add Activity Card': 'Tambah kad aktiviti',
      'Save Changes': 'Simpan perubahan',
      'Sign In': 'Log masuk',
      'Register Now': 'Daftar sekarang',
      'Forgot Password?': 'Lupa kata laluan?',
      'Save Profile': 'Simpan profil',
      'Update Password': 'Kemas kini kata laluan',
      'Achievements': 'Pencapaian',
      'Solo': 'Solo',
      'Group': 'Kumpulan',
      'Shake & Find': 'Goncang & Cari',
      'Mystery Journey': 'Perjalanan Misteri',
      'Explore map': 'Terokai peta',
      'Traveller profile': 'Profil pengembara',
      'Traditional Heritage Site': 'Tapak Warisan Tradisional',
      'Culture': 'Budaya',
      'Sightseeing': 'Bersiar-siar',
      'Food': 'Makanan',
      'Local Food': 'Makanan Tempatan',
      'Local Craft': 'Kraf Tempatan',
      'Historical Monument': 'Monumen Bersejarah',
      'Explore Malaysia your way': 'Terokai Malaysia dengan cara anda',
      'My trip': 'Perjalanan saya',
      'Trips': 'Perjalanan',
      'Travelers': 'Pengembara',
      'UPCOMING TRIP': 'PERJALANAN AKAN DATANG',
      'Manage date tabs': 'Urus tab tarikh',
      'Current location': 'Lokasi semasa',
      'auto-sorted by time': 'disusun automatik mengikut masa',
      'activity cards': 'kad aktiviti',
      'destinations': 'destinasi',
      'scheduled stops': 'hentian dijadualkan',
      'itinerary': 'jadual perjalanan',
      'View Route': 'Lihat laluan',
      'Create Itinerary Activity Card': 'Cipta kad aktiviti jadual perjalanan',
      'Activity Title *': 'Tajuk aktiviti *',
      'Searchable / Selectable Location *': 'Lokasi boleh dicari / dipilih *',
      'Search any location in Malaysia': 'Cari mana-mana lokasi di Malaysia',
      'Start Time *': 'Masa mula *',
      'Category': 'Kategori',
      'Optional Description / Notes': 'Penerangan / nota pilihan',
    },
    'zh': {
      'Discover': '探索',
      'Map': '地图',
      'Mystery': '神秘之旅',
      'Plan': '行程',
      'Profile': '个人资料',
      'Language': '语言',
      'Language Settings': '语言设置',
      'Back': '返回',
      'Create plan': '创建行程',
      'Export PDF': '导出 PDF',
      'Edit profile': '编辑个人资料',
      'Photo, name and travel bio': '照片、姓名和旅行简介',
      'Achievements & badges': '成就与徽章',
      'Challenges, progress and rewards': '挑战、进度和奖励',
      'Passport stamps': '护照印章',
      'Your verified destination collection': '您已验证的目的地收藏',
      'Log out': '退出登录',
      'Explore Discover': '探索发现',
      'Add to Plan': '添加到行程',
      'Get Directions': '获取路线',
      'Clear all': '全部清除',
      'Reset filters': '重置筛选',
      'Write Review': '撰写评价',
      'Submit Review': '提交评价',
      'Heritage Quest': '文化遗产任务',
      'Retry': '重试',
      'Cancel': '取消',
      'Edit': '编辑',
      'Resume': '继续',
      'Save preferences': '保存偏好',
      'View on Map': '在地图上查看',
      'View Passport': '查看护照',
      'Explore Another Mystery': '探索另一个神秘之旅',
      'Create New Plan': '创建新行程',
      '+ Create New Plan': '+ 创建新行程',
      'Create Travel Plan': '创建旅行计划',
      'Add Activity': '添加活动',
      'Add Date Tab': '添加日期页',
      'Join Plan': '加入行程',
      'Delete Plan': '删除行程',
      'Delete': '删除',
      'Share': '分享',
      'Remove': '移除',
      'Leave Group': '离开群组',
      'Add Activity Card': '添加活动卡',
      'Save Changes': '保存更改',
      'Sign In': '登录',
      'Register Now': '立即注册',
      'Forgot Password?': '忘记密码？',
      'Save Profile': '保存个人资料',
      'Update Password': '更新密码',
      'Achievements': '成就',
      'Solo': '单人',
      'Group': '群组',
      'Shake & Find': '摇一摇寻找',
      'Mystery Journey': '神秘之旅',
      'Explore map': '探索地图',
      'Traveller profile': '旅行者资料',
      'Traditional Heritage Site': '传统文化遗产地',
      'Culture': '文化',
      'Sightseeing': '观光',
      'Food': '美食',
      'Local Food': '当地美食',
      'Local Craft': '当地工艺',
      'Historical Monument': '历史古迹',
      'Explore Malaysia your way': '以您的方式探索马来西亚',
      'My trip': '我的行程',
      'Trips': '行程',
      'Travelers': '旅行者',
      'UPCOMING TRIP': '即将开始的行程',
      'Manage date tabs': '管理日期页',
      'Current location': '当前位置',
      'auto-sorted by time': '按时间自动排序',
      'activity cards': '活动卡',
      'destinations': '目的地',
      'scheduled stops': '个预定站点',
      'itinerary': '行程安排',
      'View Route': '查看路线',
      'Create Itinerary Activity Card': '创建行程活动卡',
      'Activity Title *': '活动标题 *',
      'Searchable / Selectable Location *': '可搜索／可选择地点 *',
      'Search any location in Malaysia': '搜索马来西亚的任何地点',
      'Start Time *': '开始时间 *',
      'Category': '类别',
      'Optional Description / Notes': '可选说明／备注',
    },
    'ta': {
      'Discover': 'கண்டறியுங்கள்',
      'Map': 'வரைபடம்',
      'Mystery': 'மர்மப் பயணம்',
      'Plan': 'திட்டம்',
      'Profile': 'சுயவிவரம்',
      'Language': 'மொழி',
      'Language Settings': 'மொழி அமைப்புகள்',
      'Back': 'பின்செல்',
      'Create plan': 'திட்டம் உருவாக்கு',
      'Export PDF': 'PDF ஏற்றுமதி',
      'Edit profile': 'சுயவிவரத்தைத் திருத்து',
      'Photo, name and travel bio': 'படம், பெயர் மற்றும் பயணக் குறிப்பு',
      'Achievements & badges': 'சாதனைகள் & பதக்கங்கள்',
      'Challenges, progress and rewards':
          'சவால்கள், முன்னேற்றம் மற்றும் வெகுமதிகள்',
      'Passport stamps': 'கடவுச்சீட்டு முத்திரைகள்',
      'Your verified destination collection':
          'உங்கள் சரிபார்க்கப்பட்ட இடங்களின் தொகுப்பு',
      'Log out': 'வெளியேறு',
      'Explore Discover': 'கண்டறிதலை ஆராயுங்கள்',
      'Add to Plan': 'திட்டத்தில் சேர்',
      'Get Directions': 'வழிகளைப் பெறு',
      'Clear all': 'அனைத்தையும் அழி',
      'Reset filters': 'வடிப்பான்களை மீட்டமை',
      'Write Review': 'மதிப்புரை எழுது',
      'Submit Review': 'மதிப்புரையைச் சமர்ப்பி',
      'Heritage Quest': 'பாரம்பரியத் தேடல்',
      'Retry': 'மீண்டும் முயற்சி',
      'Cancel': 'ரத்துசெய்',
      'Edit': 'திருத்து',
      'Resume': 'தொடர்க',
      'Save preferences': 'விருப்பங்களைச் சேமி',
      'View on Map': 'வரைபடத்தில் காண்க',
      'View Passport': 'கடவுச்சீட்டைக் காண்க',
      'Explore Another Mystery': 'மற்றொரு மர்மத்தை ஆராயுங்கள்',
      'Create New Plan': 'புதிய திட்டத்தை உருவாக்கு',
      '+ Create New Plan': '+ புதிய திட்டம்',
      'Create Travel Plan': 'பயணத் திட்டத்தை உருவாக்கு',
      'Add Activity': 'செயல்பாட்டைச் சேர்',
      'Add Date Tab': 'தேதி தாவலைச் சேர்',
      'Join Plan': 'திட்டத்தில் சேர்',
      'Delete Plan': 'திட்டத்தை நீக்கு',
      'Delete': 'நீக்கு',
      'Share': 'பகிர்',
      'Remove': 'அகற்று',
      'Leave Group': 'குழுவை விட்டு வெளியேறு',
      'Add Activity Card': 'செயல்பாட்டு அட்டையைச் சேர்',
      'Save Changes': 'மாற்றங்களைச் சேமி',
      'Sign In': 'உள்நுழைக',
      'Register Now': 'இப்போது பதிவு செய்க',
      'Forgot Password?': 'கடவுச்சொல் மறந்ததா?',
      'Save Profile': 'சுயவிவரத்தைச் சேமி',
      'Update Password': 'கடவுச்சொல்லைப் புதுப்பி',
      'Achievements': 'சாதனைகள்',
      'Solo': 'தனி',
      'Group': 'குழு',
      'Shake & Find': 'குலுக்கி கண்டறி',
      'Mystery Journey': 'மர்மப் பயணம்',
      'Explore map': 'வரைபடத்தை ஆராயுங்கள்',
      'Traveller profile': 'பயணியர் சுயவிவரம்',
      'Traditional Heritage Site': 'பாரம்பரிய மரபுத் தலம்',
      'Culture': 'கலாச்சாரம்',
      'Sightseeing': 'சுற்றுலா',
      'Food': 'உணவு',
      'Local Food': 'உள்ளூர் உணவு',
      'Local Craft': 'உள்ளூர் கைவினை',
      'Historical Monument': 'வரலாற்றுச் சின்னம்',
      'Explore Malaysia your way': 'மலேசியாவை உங்கள் வழியில் ஆராயுங்கள்',
      'My trip': 'என் பயணம்',
      'Trips': 'பயணங்கள்',
      'Travelers': 'பயணிகள்',
      'UPCOMING TRIP': 'வரவிருக்கும் பயணம்',
      'Manage date tabs': 'தேதி தாவல்களை நிர்வகி',
      'Current location': 'தற்போதைய இடம்',
      'auto-sorted by time': 'நேரப்படி தானாக வரிசைப்படுத்தப்பட்டது',
      'activity cards': 'செயல்பாட்டு அட்டைகள்',
      'destinations': 'இலக்குகள்',
      'scheduled stops': 'திட்டமிட்ட நிறுத்தங்கள்',
      'itinerary': 'பயண அட்டவணை',
      'View Route': 'வழியைக் காண்க',
      'Create Itinerary Activity Card': 'பயணச் செயல்பாட்டு அட்டையை உருவாக்கு',
      'Activity Title *': 'செயல்பாட்டுத் தலைப்பு *',
      'Searchable / Selectable Location *':
          'தேடக்கூடிய / தேர்ந்தெடுக்கக்கூடிய இடம் *',
      'Search any location in Malaysia':
          'மலேசியாவில் எந்த இடத்தையும் தேடுங்கள்',
      'Start Time *': 'தொடக்க நேரம் *',
      'Category': 'வகை',
      'Optional Description / Notes': 'விருப்ப விளக்கம் / குறிப்புகள்',
    },
  };

  String text(String english) {
    final values = _values[locale.languageCode];
    if (values == null) return english;
    final exact = values[english];
    if (exact != null) return exact;
    final lower = english.toLowerCase();
    for (final entry in values.entries) {
      if (entry.key.toLowerCase() == lower) return entry.value;
    }
    var result = english;
    for (final entry in values.entries) {
      if (entry.key.length < 5) continue;
      result = result.replaceAll(entry.key, entry.value);
    }
    return result;
  }
}

extension LocalizedBuildContext on BuildContext {
  String tr(String english) => AppLocalization.of(this).text(english);
}
