import 'package:flutter/widgets.dart';

class AppLocalization {
  const AppLocalization(this.locale);

  final Locale locale;

  static AppLocalization of(BuildContext context) =>
      AppLocalization(Localizations.localeOf(context));

  static const Map<String, Map<String, String>> _values = {
    'ms': {
      'Discover': 'Terokai',
      'Map': 'Peta',
      'Mystery': 'Misteri',
      'Plan': 'Pelan',
      'Profile': 'Profil',
      'Language': 'Bahasa',
      'Language Settings': 'Tetapan Bahasa',
      'Back': 'Kembali',
      'Create plan': 'Cipta pelan',
      'Export PDF': 'Eksport PDF',
      'Edit profile': 'Sunting profil',
      'Photo, name and travel bio': 'Foto, nama dan biodata perjalanan',
      'Achievements & badges': 'Pencapaian & lencana',
      'Challenges, progress and rewards': 'Cabaran, kemajuan dan ganjaran',
      'Passport stamps': 'Cop pasport',
      'Your verified destination collection': 'Koleksi destinasi disahkan anda',
      'Log out': 'Log keluar',
      'Explore Discover': 'Terokai penemuan',
      'Add to Plan': 'Tambah ke pelan',
      'Get Directions': 'Dapatkan arah',
      'Clear all': 'Kosongkan semua',
      'Reset filters': 'Tetapkan semula penapis',
      'Write Review': 'Tulis ulasan',
      'Submit Review': 'Hantar ulasan',
      'Heritage Quest': 'Misi warisan',
      'Retry': 'Cuba lagi',
      'Cancel': 'Batal',
      'Edit': 'Sunting',
      'Resume': 'Sambung',
      'Save preferences': 'Simpan pilihan',
      'View on Map': 'Lihat pada peta',
      'View Passport': 'Lihat pasport',
      'Explore Another Mystery': 'Terokai misteri lain',
      'Create New Plan': 'Cipta pelan baharu',
      '+ Create New Plan': '+ Cipta pelan baharu',
      'Create Travel Plan': 'Cipta pelan perjalanan',
      'Add Activity': 'Tambah aktiviti',
      'Add Date Tab': 'Tambah tab tarikh',
      'Join Plan': 'Sertai pelan',
      'Delete Plan': 'Padam pelan',
      'Delete': 'Padam',
      'Share': 'Kongsi',
      'Remove': 'Alih keluar',
      'Leave Group': 'Tinggalkan kumpulan',
      'Add Activity Card': 'Tambah kad aktiviti',
      'Save Changes': 'Simpan perubahan',
      'Sign In': 'Log masuk',
      'Register Now': 'Daftar sekarang',
      'Forgot Password?': 'Lupa kata laluan?',
      'Save Profile': 'Simpan profil',
      'Update Password': 'Kemas kini kata laluan',
      'Achievements': 'Pencapaian',
      'Solo': 'Solo',
      'Group': 'Kumpulan',
      'Shake & Find': 'Goncang & Cari',
      'Mystery Journey': 'Perjalanan Misteri',
      'Explore map': 'Terokai peta',
      'Traveller profile': 'Profil pengembara',
      'Traditional Heritage Site': 'Tapak Warisan Tradisional',
      'Culture': 'Budaya',
      'Sightseeing': 'Bersiar-siar',
      'Food': 'Makanan',
      'Local Food': 'Makanan Tempatan',
      'Local Craft': 'Kraf Tempatan',
      'Historical Monument': 'Monumen Bersejarah',
      'Heritage Workshops': 'Bengkel Warisan',
      'Revisit Challenge': 'Cabaran Lawatan Semula',
      "You've explored this place before.": 'Anda pernah menerokai tempat ini.',
      'Play This Revisit': 'Main Lawatan Semula Ini',
      'Shake Again for a New Place': 'Goncang Lagi untuk Tempat Baharu',
      'Looking for another mystery...': 'Mencari misteri lain...',
      'No other new mystery locations are available nearby right now.':
          'Tiada lokasi misteri baharu lain yang tersedia berdekatan sekarang.',
      'Try Again': 'Cuba Lagi',
      'Adjust Preferences': 'Laraskan Pilihan',
      'New Mystery Found': 'Misteri Baharu Ditemui',
      'Live mystery': 'Misteri langsung',
      'Your hidden destination': 'Destinasi tersembunyi anda',
      'Journey progress': 'Kemajuan perjalanan',
      'Started': 'Bermula',
      'Clues': 'Petunjuk',
      'Route': 'Laluan',
      'Arrived': 'Tiba',
      'Check Arrival': 'Semak Ketibaan',
      'Leave and continue later': 'Keluar dan sambung kemudian',
      'No locations found.': 'Tiada lokasi ditemui.',
      'No locations match the selected category.':
          'Tiada lokasi sepadan dengan kategori dipilih.',
      'Destination added to your bookmarks.':
          'Destinasi ditambah pada penanda buku anda.',
      'Review submitted successfully.': 'Ulasan berjaya dihantar.',
      'Email': 'E-mel',
      'Password': 'Kata laluan',
      'Back to Login': 'Kembali ke log masuk',
      'Create New Account': 'Cipta Akaun Baharu',
      'Reset Password': 'Tetapkan Semula Kata Laluan',
      'Passwords do not match.': 'Kata laluan tidak sepadan.',
      'About this place': 'Tentang tempat ini',
      'Opening hours': 'Waktu operasi',
      'Plan your visit': 'Rancang lawatan anda',
      'Traveller reviews': 'Ulasan pengembara',
      'Saved places': 'Tempat disimpan',
      'Search the map': 'Cari dalam peta',
      'Centre on me': 'Pusatkan pada saya',
      'Start Route': 'Mulakan Laluan',
      'Shake your phone!': 'Goncang telefon anda!',
      'Motion sensor active': 'Penderia gerakan aktif',
      'Group Chat': 'Sembang Kumpulan',
      'Ready': 'Sedia',
      'Not ready': 'Belum sedia',
      'All clues discovered': 'Semua petunjuk telah ditemui',
    },
    'zh': {
      'Discover': '探索',
      'Map': '地图',
      'Mystery': '神秘之旅',
      'Plan': '行程',
      'Profile': '个人资料',
      'Language': '语言',
      'Language Settings': '语言设置',
      'Back': '返回',
      'Create plan': '创建行程',
      'Export PDF': '导出 PDF',
      'Edit profile': '编辑个人资料',
      'Photo, name and travel bio': '照片、姓名和旅行简介',
      'Achievements & badges': '成就与徽章',
      'Challenges, progress and rewards': '挑战、进度和奖励',
      'Passport stamps': '护照印章',
      'Your verified destination collection': '您已验证的目的地收藏',
      'Log out': '退出登录',
      'Explore Discover': '探索发现',
      'Add to Plan': '添加到行程',
      'Get Directions': '获取路线',
      'Clear all': '全部清除',
      'Reset filters': '重置筛选',
      'Write Review': '撰写评价',
      'Submit Review': '提交评价',
      'Heritage Quest': '文化遗产任务',
      'Retry': '重试',
      'Cancel': '取消',
      'Edit': '编辑',
      'Resume': '继续',
      'Save preferences': '保存偏好',
      'View on Map': '在地图上查看',
      'View Passport': '查看护照',
      'Explore Another Mystery': '探索另一个神秘之旅',
      'Create New Plan': '创建新行程',
      '+ Create New Plan': '+ 创建新行程',
      'Create Travel Plan': '创建旅行计划',
      'Add Activity': '添加活动',
      'Add Date Tab': '添加日期页',
      'Join Plan': '加入行程',
      'Delete Plan': '删除行程',
      'Delete': '删除',
      'Share': '分享',
      'Remove': '移除',
      'Leave Group': '离开群组',
      'Add Activity Card': '添加活动卡',
      'Save Changes': '保存更改',
      'Sign In': '登录',
      'Register Now': '立即注册',
      'Forgot Password?': '忘记密码？',
      'Save Profile': '保存个人资料',
      'Update Password': '更新密码',
      'Achievements': '成就',
      'Solo': '单人',
      'Group': '群组',
      'Shake & Find': '摇一摇寻找',
      'Mystery Journey': '神秘之旅',
      'Explore map': '探索地图',
      'Traveller profile': '旅行者资料',
      'Traditional Heritage Site': '传统文化遗产地',
      'Culture': '文化',
      'Sightseeing': '观光',
      'Food': '美食',
      'Local Food': '当地美食',
      'Local Craft': '当地工艺',
      'Historical Monument': '历史古迹',
      'Heritage Workshops': '传统工艺工作坊',
      'Revisit Challenge': '重游挑战',
      "You've explored this place before.": '你以前探索过这个地方。',
      'Play This Revisit': '接受重游挑战',
      'Shake Again for a New Place': '再次摇动寻找新地点',
      'Looking for another mystery...': '正在寻找另一个神秘地点……',
      'No other new mystery locations are available nearby right now.':
          '附近目前没有其他新的神秘地点。',
      'Try Again': '再试一次',
      'Adjust Preferences': '调整偏好',
      'New Mystery Found': '发现新的神秘地点',
      'Live mystery': '进行中的神秘之旅',
      'Your hidden destination': '你的隐藏目的地',
      'Journey progress': '旅程进度',
      'Started': '已开始',
      'Clues': '线索',
      'Route': '路线',
      'Arrived': '已到达',
      'Check Arrival': '检查到达状态',
      'Leave and continue later': '暂时离开，稍后继续',
      'No locations found.': '未找到地点。',
      'No locations match the selected category.': '没有符合所选分类的地点。',
      'Destination added to your bookmarks.': '目的地已添加到书签。',
      'Review submitted successfully.': '评价提交成功。',
      'Email': '电子邮箱',
      'Password': '密码',
      'Back to Login': '返回登录',
      'Create New Account': '创建新账号',
      'Reset Password': '重置密码',
      'Passwords do not match.': '两次输入的密码不一致。',
      'About this place': '关于这个地点',
      'Opening hours': '开放时间',
      'Plan your visit': '规划你的参观',
      'Traveller reviews': '旅行者评价',
      'Saved places': '已收藏地点',
      'Search the map': '搜索地图',
      'Centre on me': '定位到我的位置',
      'Start Route': '开始路线',
      'Shake your phone!': '摇动你的手机！',
      'Motion sensor active': '动作传感器已启用',
      'Group Chat': '群组聊天',
      'Ready': '已准备',
      'Not ready': '未准备',
      'All clues discovered': '所有线索均已发现',
    },
    'ta': {
      'Discover': 'கண்டறியுங்கள்',
      'Map': 'வரைபடம்',
      'Mystery': 'மர்மப் பயணம்',
      'Plan': 'திட்டம்',
      'Profile': 'சுயவிவரம்',
      'Language': 'மொழி',
      'Language Settings': 'மொழி அமைப்புகள்',
      'Back': 'பின்செல்',
      'Create plan': 'திட்டம் உருவாக்கு',
      'Export PDF': 'PDF ஏற்றுமதி',
      'Edit profile': 'சுயவிவரத்தைத் திருத்து',
      'Photo, name and travel bio': 'படம், பெயர் மற்றும் பயணக் குறிப்பு',
      'Achievements & badges': 'சாதனைகள் & பதக்கங்கள்',
      'Challenges, progress and rewards':
          'சவால்கள், முன்னேற்றம் மற்றும் வெகுமதிகள்',
      'Passport stamps': 'கடவுச்சீட்டு முத்திரைகள்',
      'Your verified destination collection':
          'உங்கள் சரிபார்க்கப்பட்ட இடங்களின் தொகுப்பு',
      'Log out': 'வெளியேறு',
      'Explore Discover': 'கண்டறிதலை ஆராயுங்கள்',
      'Add to Plan': 'திட்டத்தில் சேர்',
      'Get Directions': 'வழிகளைப் பெறு',
      'Clear all': 'அனைத்தையும் அழி',
      'Reset filters': 'வடிப்பான்களை மீட்டமை',
      'Write Review': 'மதிப்புரை எழுது',
      'Submit Review': 'மதிப்புரையைச் சமர்ப்பி',
      'Heritage Quest': 'பாரம்பரியத் தேடல்',
      'Retry': 'மீண்டும் முயற்சி',
      'Cancel': 'ரத்துசெய்',
      'Edit': 'திருத்து',
      'Resume': 'தொடர்க',
      'Save preferences': 'விருப்பங்களைச் சேமி',
      'View on Map': 'வரைபடத்தில் காண்க',
      'View Passport': 'கடவுச்சீட்டைக் காண்க',
      'Explore Another Mystery': 'மற்றொரு மர்மத்தை ஆராயுங்கள்',
      'Create New Plan': 'புதிய திட்டத்தை உருவாக்கு',
      '+ Create New Plan': '+ புதிய திட்டம்',
      'Create Travel Plan': 'பயணத் திட்டத்தை உருவாக்கு',
      'Add Activity': 'செயல்பாட்டைச் சேர்',
      'Add Date Tab': 'தேதி தாவலைச் சேர்',
      'Join Plan': 'திட்டத்தில் சேர்',
      'Delete Plan': 'திட்டத்தை நீக்கு',
      'Delete': 'நீக்கு',
      'Share': 'பகிர்',
      'Remove': 'அகற்று',
      'Leave Group': 'குழுவை விட்டு வெளியேறு',
      'Add Activity Card': 'செயல்பாட்டு அட்டையைச் சேர்',
      'Save Changes': 'மாற்றங்களைச் சேமி',
      'Sign In': 'உள்நுழைக',
      'Register Now': 'இப்போது பதிவு செய்க',
      'Forgot Password?': 'கடவுச்சொல் மறந்ததா?',
      'Save Profile': 'சுயவிவரத்தைச் சேமி',
      'Update Password': 'கடவுச்சொல்லைப் புதுப்பி',
      'Achievements': 'சாதனைகள்',
      'Solo': 'தனி',
      'Group': 'குழு',
      'Shake & Find': 'குலுக்கி கண்டறி',
      'Mystery Journey': 'மர்மப் பயணம்',
      'Explore map': 'வரைபடத்தை ஆராயுங்கள்',
      'Traveller profile': 'பயணியர் சுயவிவரம்',
      'Traditional Heritage Site': 'பாரம்பரிய மரபுத் தலம்',
      'Culture': 'கலாச்சாரம்',
      'Sightseeing': 'சுற்றுலா',
      'Food': 'உணவு',
      'Local Food': 'உள்ளூர் உணவு',
      'Local Craft': 'உள்ளூர் கைவினை',
      'Historical Monument': 'வரலாற்றுச் சின்னம்',
      'Heritage Workshops': 'பாரம்பரியப் பட்டறைகள்',
      'Revisit Challenge': 'மீள்வருகை சவால்',
      "You've explored this place before.":
          'இந்த இடத்தை நீங்கள் முன்பே ஆராய்ந்துள்ளீர்கள்.',
      'Play This Revisit': 'இந்த மீள்வருகையைத் தொடங்கு',
      'Shake Again for a New Place': 'புதிய இடத்திற்காக மீண்டும் குலுக்கவும்',
      'Looking for another mystery...': 'மற்றொரு மர்மத்தைத் தேடுகிறது...',
      'No other new mystery locations are available nearby right now.':
          'அருகில் வேறு புதிய மர்ம இடங்கள் இப்போது இல்லை.',
      'Try Again': 'மீண்டும் முயற்சி',
      'Adjust Preferences': 'விருப்பங்களை மாற்று',
      'New Mystery Found': 'புதிய மர்மம் கண்டறியப்பட்டது',
      'Live mystery': 'நடப்பு மர்மம்',
      'Your hidden destination': 'உங்கள் மறைக்கப்பட்ட இலக்கு',
      'Journey progress': 'பயண முன்னேற்றம்',
      'Started': 'தொடங்கியது',
      'Clues': 'குறிப்புகள்',
      'Route': 'வழி',
      'Arrived': 'வந்தடைந்தது',
      'Check Arrival': 'வருகையைச் சரிபார்',
      'Leave and continue later': 'வெளியேறி பின்னர் தொடரவும்',
      'No locations found.': 'இடங்கள் எதுவும் கிடைக்கவில்லை.',
      'No locations match the selected category.':
          'தேர்ந்தெடுத்த வகைக்கு இடங்கள் எதுவும் பொருந்தவில்லை.',
      'Destination added to your bookmarks.':
          'இலக்கு உங்கள் புத்தகக்குறிகளில் சேர்க்கப்பட்டது.',
      'Review submitted successfully.':
          'மதிப்புரை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.',
      'Email': 'மின்னஞ்சல்',
      'Password': 'கடவுச்சொல்',
      'Back to Login': 'உள்நுழைவுக்குத் திரும்பு',
      'Create New Account': 'புதிய கணக்கை உருவாக்கு',
      'Reset Password': 'கடவுச்சொல்லை மீட்டமை',
      'Passwords do not match.': 'கடவுச்சொற்கள் பொருந்தவில்லை.',
      'About this place': 'இந்த இடத்தைப் பற்றி',
      'Opening hours': 'திறந்திருக்கும் நேரம்',
      'Plan your visit': 'உங்கள் வருகையைத் திட்டமிடுங்கள்',
      'Traveller reviews': 'பயணியர் மதிப்புரைகள்',
      'Saved places': 'சேமித்த இடங்கள்',
      'Search the map': 'வரைபடத்தில் தேடு',
      'Centre on me': 'என்னை மையப்படுத்து',
      'Start Route': 'வழியைத் தொடங்கு',
      'Shake your phone!': 'உங்கள் தொலைபேசியைக் குலுக்குங்கள்!',
      'Motion sensor active': 'இயக்க உணரி செயலில் உள்ளது',
      'Group Chat': 'குழு அரட்டை',
      'Ready': 'தயார்',
      'Not ready': 'தயாரில்லை',
      'All clues discovered': 'அனைத்து குறிப்புகளும் கண்டறியப்பட்டன',
    },
  };

  String text(String english) {
    final values = _values[locale.languageCode];
    if (values == null) return english;
    final exact = values[english];
    if (exact != null) return exact;
    return _dynamicText(english, locale.languageCode);
  }

  static String _dynamicText(String english, String language) {
    String? match(String pattern) =>
        RegExp(pattern).firstMatch(english)?.group(1);
    final seconds = match(r'^Resend available in (\d+)s$');
    if (seconds != null) {
      return switch (language) {
        'ms' => 'Hantar semula tersedia dalam ${seconds}s',
        'zh' => '$seconds秒后可重新发送',
        'ta' => '$seconds வினாடிகளில் மீண்டும் அனுப்பலாம்',
        _ => english,
      };
    }
    final metres = match(r'^(\d+) m away$');
    if (metres != null) {
      return switch (language) {
        'ms' => '$metres m lagi',
        'zh' => '距离 $metres 米',
        'ta' => '$metres மீ தொலைவில்',
        _ => english,
      };
    }
    final explored = match(r'^Explored (\d+) times$');
    if (explored != null) {
      return switch (language) {
        'ms' => 'Diterokai $explored kali',
        'zh' => '已探索 $explored 次',
        'ta' => '$explored முறை ஆராயப்பட்டது',
        _ => english,
      };
    }
    final reviews = match(r'^(\d+) reviews$');
    if (reviews != null) {
      return switch (language) {
        'ms' => '$reviews ulasan',
        'zh' => '$reviews 条评价',
        'ta' => '$reviews மதிப்புரைகள்',
        _ => english,
      };
    }
    final completedOn = match(r'^Completed on (.+)$');
    if (completedOn != null) {
      return switch (language) {
        'ms' => 'Selesai pada $completedOn',
        'zh' => '完成于 $completedOn',
        'ta' => '$completedOn அன்று முடிக்கப்பட்டது',
        _ => english,
      };
    }
    final membersReady = match(r'^(\d+) members ready$');
    if (membersReady != null) {
      return switch (language) {
        'ms' => '$membersReady ahli bersedia',
        'zh' => '$membersReady 位成员已准备',
        'ta' => '$membersReady உறுப்பினர்கள் தயார்',
        _ => english,
      };
    }
    final withinRadius = match(r'^Within (\d+) km$');
    if (withinRadius != null) {
      return switch (language) {
        'ms' => 'Dalam lingkungan $withinRadius km',
        'zh' => '$withinRadius 公里以内',
        'ta' => '$withinRadius கிமீக்குள்',
        _ => english,
      };
    }
    final groupShake = RegExp(
      r'^Group Shake — (\d+)/(\d+) shaken$',
    ).firstMatch(english);
    if (groupShake != null) {
      final shaken = groupShake.group(1)!;
      final total = groupShake.group(2)!;
      return switch (language) {
        'ms' => 'Goncangan Kumpulan — $shaken/$total telah goncang',
        'zh' => '群组摇动 — $shaken/$total 已完成',
        'ta' => 'குழு குலுக்கல் — $shaken/$total முடித்தனர்',
        _ => english,
      };
    }
    return english;
  }
}

extension LocalizedBuildContext on BuildContext {
  String tr(String english) => AppLocalization.of(this).text(english);
}
